"""add_transactions

Revision ID: 63e0aba61c8f
Revises: f690dd6e01fa
Create Date: 2023-10-20 17:58:52.471812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e0aba61c8f'
down_revision = 'f690dd6e01fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('referer_user_id', sa.Integer(), nullable=True),
    sa.Column('sender_account_id', sa.Integer(), nullable=True),
    sa.Column('referer_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referer_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['referer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
